name: Build, test and deploy to production (digdir) on merge to master branch

on:
  push:
    branches:
      - master

jobs:
  build-test-and-deploy-production:
    name: Build, test, publish and deploy to production environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: gcloud auth configure-docker

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Package with maven
        run: mvn clean package --no-transfer-progress

      - name: Build Docker image with latest tag
        run: docker build -f Dockerfile.prod . -t eu.gcr.io/digdir-fdk-infra/dataservice-catalog:$GITHUB_SHA -t eu.gcr.io/digdir-fdk-infra/dataservice-catalog:latest

      - name: Set max map count for elasticsearch
        run: sudo sysctl -w vm.max_map_count=262144
        
      - name: Run tests
        run: mvn -DtestImageName="eu.gcr.io/digdir-fdk-infra/dataservice-catalog:latest" verify --no-transfer-progress

      - name: Publish docker image to Google Cloud
        run: docker -- push eu.gcr.io/digdir-fdk-infra/dataservice-catalog

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
            helm fetch --untar --untardir ./helm fdk/dataservice-catalog
            helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/dataservice-catalog:$GITHUB_SHA" -f ./helm/dataservice-catalog/values/prod-digdir.yaml ./helm/dataservice-catalog/ > ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
          project_id: digdir-fdk-prod
          location_zone: europe-north1-a
          cluster_name: digdir-fdk-prod

      - name: Deploy to production
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Notify slack of deploy
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C7NTH118T\",\"text\":\"Application: dataservice-catalog deployed to digdir-production\"}'

      - name: Trigger deploy to demo
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: deploy-demo-digdir
          client-payload: '{"sha": "${{ github.sha }}"}'